# Generated by Django 4.2.28 on 2026-02-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0010_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='email',
            field=models.EmailField(max_length=250),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_pic'),
        ),
        migrations.AlterField(
            model_name='news',
            name='postedby',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='postimage',
            field=models.ImageField(blank=True, null=True, upload_to='media/news'),
        ),
        migrations.AlterField(
            model_name='news',
            name='posttitle',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='updatedby',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='page',
            name='aboutus',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='page',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='page',
            name='mobilenumber',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
